#!/bin/bash

# Show translations to other languages of the last word queried with 'es'

last=`ls -tR $HOME/.es/*.htm | head -n 1`
if [ -n "$last" ]; then
  w3m -dump -cols 180 $last | grep -A 1000 'Traducciones' | tail -n +15 | head -n -3
fi
